global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - 'alert_rules.yml'

scrape_configs:
  # Métricas da aplicação Flask diretas (não via Traefik)
  - job_name: 'flask-app-1'
    metrics_path: /metrics
    static_configs:
      - targets: ['projeto_flask-app-1_1:8000']

  - job_name: 'flask-app-2'
    metrics_path: /metrics
    static_configs:
      - targets: ['projeto_flask-app-2_1:8000']

  # Métricas dos containers via cAdvisor
  - job_name: 'cadvisor'
    metrics_path: /metrics
    static_configs:
      - targets: ['cadvisor:8080']

  # Métricas do próprio Prometheus
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['prometheus:9090']

  # Métricas do AlertManager
  - job_name: 'alertmanager'
    metrics_path: /metrics
    static_configs:
      - targets: ['alertmanager:9093']